#!/bin/bash

xdg-mime install source/azpazeta-mime.xml
xdg-mime install source/azpazeta-text-mime-xml
xdg-mime default Azpazeta.desktop application/x-azpazeta-savefile
xdg-mime default Azpazeta.desktop text/x-azpazeta-savefile
